LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := HyperOsGallery
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := HyperOsGallery/HyperOSGallery [CN Full] v3.7.0.2.apk
LOCAL_OVERRIDES_PACKAGES := Gallery
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := HyperOsGallery
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := HyperOsGallery/GalleryPlayerService.apk
LOCAL_OVERRIDES_PACKAGES := Gallery
include $(BUILD_PREBUILT)
