LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := HyperOsGallery
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := HyperOsGallery/Gallery
LOCAL_OVERRIDES_PACKAGES := Gallery
include $(BUILD_PREBUILT)
